# Generated by Django 4.1.5 on 2023-03-17 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('user_id', models.CharField(max_length=30, unique=True, verbose_name='user ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Authentication_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('passWord', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateID', models.PositiveIntegerField(unique=True)),
                ('cateName', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodID', models.PositiveIntegerField(unique=True)),
                ('prodName', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('Brand', models.CharField(max_length=100)),
                ('Condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used'), ('Open Not Used', 'Open Not Used')], max_length=50)),
                ('Price', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resell.category')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addAt', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resell.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingAddr', models.CharField(max_length=200)),
                ('subtotal', models.PositiveIntegerField()),
                ('disacount', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('orederStatus', models.CharField(choices=[('Order Resived', 'Order Resived'), ('Order processing', 'Order processing'), ('Order on the way', 'Order on the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('orderdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resell.wishlist')),
            ],
        ),
    ]
