# Generated by Django 4.1.5 on 2023-03-21 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='user id')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('joined_on', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Authentication_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('passWord', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateID', models.PositiveIntegerField(unique=True)),
                ('cateName', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(default=0, unique=True, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('category', models.CharField(blank=True, choices=[('Home and Furniture', 'Home and Furniture'), ('Technology', 'Technology'), ('Clothing', 'Clothing'), ('Other', 'Other')], max_length=50, verbose_name='category')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='brand')),
                ('condition', models.CharField(blank=True, choices=[('Brand New and Sealed', 'Brand New and Sealed'), ('Like New', 'Like New'), ('Signs of Usage', 'Signs of Usage'), ('Broken/For Parts Only', 'Broken/For Parts Only')], max_length=50, verbose_name='condition')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='price')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('image', models.ImageField(upload_to='products', verbose_name='image')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addAt', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resell.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingAddr', models.CharField(max_length=200)),
                ('subtotal', models.PositiveIntegerField()),
                ('disacount', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('orederStatus', models.CharField(choices=[('Order Resived', 'Order Resived'), ('Order processing', 'Order processing'), ('Order on the way', 'Order on the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('orderdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resell.wishlist')),
            ],
        ),
    ]
