# Generated by Django 2.2.28 on 2023-03-05 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('passWord', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateID', models.IntegerField(default=20, unique=True)),
                ('cateName', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodID', models.IntegerField(default=20, unique=True)),
                ('prodName', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('Brand', models.CharField(max_length=100)),
                ('Condition', models.CharField(max_length=100)),
                ('Price', models.PositiveIntegerField()),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resell.Category')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('BirthOfData', models.DateTimeField()),
                ('Address', models.CharField(blank=True, max_length=1000)),
                ('UserID', models.IntegerField(default=20, unique=True)),
                ('phoneNum', models.IntegerField(max_length=100)),
                ('creditRating', models.IntegerField(max_length=10)),
                ('Email', models.CharField(max_length=100)),
                ('joinedOn', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addAt', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resell.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resell.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdBy', models.CharField(max_length=200)),
                ('shippingAddr', models.CharField(max_length=200)),
                ('subtotal', models.PositiveIntegerField()),
                ('disacount', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('orederStatus', models.CharField(choices=[('Order Resived', 'Order Resived'), ('Order processing', 'Order processing'), ('Order on the way', 'Order on the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('wishlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resell.Wishlist')),
            ],
        ),
    ]
