# Generated by Django 4.1.5 on 2023-03-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='user id'),
        ),
    ]
