# Generated by Django 2.2.28 on 2023-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creditRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.IntegerField(),
        ),
    ]
