# Generated by Django 4.1.5 on 2023-03-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
