# Generated by Django 2.2.28 on 2023-03-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0002_auto_20230305_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cateID',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodID',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.CharField(max_length=50),
        ),
    ]
