# Generated by Django 4.1.5 on 2023-03-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0002_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joinedOn',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
