# Generated by Django 2.2.28 on 2023-03-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0003_auto_20230305_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used'), ('Open Not Used', 'Open Not Used')], max_length=50),
        ),
    ]
