# Generated by Django 4.1.5 on 2023-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0003_customuser_joinedon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='joinedOn',
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined_on',
            field=models.DateField(auto_now=True),
        ),
    ]
