# Generated by Django 2.2.28 on 2023-03-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0004_auto_20230305_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
