# Generated by Django 4.1.5 on 2023-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0004_remove_customuser_joinedon_customuser_joined_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
