# Generated by Django 2.2.28 on 2023-03-05 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0005_auto_20230305_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resell.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wishlist',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='resell.Wishlist'),
        ),
    ]
