# Generated by Django 4.1.5 on 2023-03-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
