# Generated by Django 2.2.28 on 2023-03-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0007_auto_20230314_0658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
