# Generated by Django 4.1.5 on 2023-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0007_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/pfps'),
        ),
    ]
