# Generated by Django 4.1.5 on 2023-03-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0008_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
